export const ADD_TODO = "ADD_TODO"
export const DELETE_TODO = "DELETE_TODO";
export const COMPLETED_TODO = "COMPLETED_TODO";
export const NON_VISIBLE_TODO = "NON_VISIBLE_TODO";
export const DELETE_COMPLETED_TODOS = "DELETE_COMPLETED_TODOS";